#!/bin/bash
sudo wget https://raw.githubusercontent.com/GuillermoVazquez/systemsProgramming/master/apache.conf
sudo apt-get update
sudo apt-get install apache2
sudo apt install gcc g++ make zip unzip mysql-server \
        apache2 php php-cli libapache2-mod-php \
        php-gd php-curl php-mysql php-json php-zip \
        php-gmp php-xml php-mbstring \
        bsdmainutils ntp phpmyadmin libcgroup-dev \
        linuxdoc-tools linuxdoc-tools-text \
        groff texlive-latex-recommended texlive-latex-extra \
        texlive-fonts-recommended texlive-lang-european
sudo phpenmod json
sudo apt install make sudo debootstrap libcgroup-dev \
        php-cli php-curl php-json php-xml php-zip procps \
        gcc g++ openjdk-8-jre-headless \
        openjdk-8-jdk ghc fp-compiler
sudo apt install libcurl4-gnutls-dev libjsoncpp-dev libmagic-dev
cd /
cd usr/share
sudo wget https://www.domjudge.org/releases/domjudge-5.3.2.tar.gz
sudo tar -xvf domjudge-5.3.2.tar.gz
cd domjudge-5.3.2
sudo ./configure --prefix=/usr/share/dom --with-baseurl=BASEURL --with-domjudge-user=root
sudo make all
sudo make install-domserver
sudo make install-judgehost
sudo make install-docs
cd ../dom
sudo apt install dc
cd domserver/bin
sudo ./dj_setup_database  -r install
sudo ln -s etc/apache.conf /etc/apache2/conf-available/domjudge.conf
cd
sudo su
sudo cat apache.conf >> ../../etc/apache2/apache2.conf
sudo service apache2 reload
exit
sudo useradd -d /nonexistent -g nogroup -s /bin/false domjudge-run
sudo groupadd domjudge-run
sudo apt update
sudo apt upgrade
cd /usr/share/dom/judgehost/etc
sudo chmod 0440 sudoers-domjudge
sudo mv sudoers-domjudge /etc/sudoers.d/
sudo update-grub
cd /usr/share/dom/judgehost/bin 
sudo ./dj_make_chroot
cd etc/default/
sudo sed -i 's/"console=tty1 console=ttyS0"/"quiet cgroup_enable=memory swapaccount=1"/g' grub
sudo update-grub
sudo reboot

cd /etc/default/grub.d
sudo sed -i 's/"console=tty1 console=ttyS0 nvme.io_timeout=4294967295"/"quiet cgroup_enable=memory swapaccount=1"/g' 50-cloudimg-settings.cfg 
sudo update-grub
sudo reboot

//check in /proc/cmdline
//cd into dom judgehost bin /.create_cgroups
//start judgedaemon
